name: phototrek_flutter
description: "PhotoTrek Journey: Cross-Platform Expedition Cartographer, VRP Optimization & STEM Science Lab for iOS, Android, and Web."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
